#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------

#restore0Dir

runApplication blockMesh
runApplication makeFaMesh
runApplication decomposePar
runParallel $(getApplication)
touch case.foam
reconstructPar
#extractCapRiseApex   ## Utility to get csv file of apex heights. not in parallel yet
#runApplication $(getApplication)

#------------------------------------------------------------------------------
